name: Node CD

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm run build
      env:
        CI: true
    - name: Publish
      run: |
        npm run dist
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Cleanup artifacts
      run: |
        npx rimraf "dist/!(*.exe|*.deb|*.AppImage|*.dmg)"
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: dist
